### ISSUE TITLE
Unable to build pfg for ast.ClassDef

### ISSUE THREAD

**Issue by abiUni** [JetBrains-Research/python-change-miner#10]
Hello, 
thank you for developing this powerful tool! 

Unfortunately, I seem unable to discover any patterns from local files even though I set the minimum frequency to 1.
The Gumtree set up works fine. However, when I run the following command  (intentionally duplicate source/dest to test),
I get no patterns:

> python3 main.py patterns -s ./python_examples/test31.py ./python_examples/test31.py -d ./python_examples/test32.py ./python_examples/test32.py
[04.05.2023 18:29:47] WARNING: pid3138: Change graph building... 
[04.05.2023 18:29:47] WARNING: pid3138: Flow graphs... OK 108ms 
[04.05.2023 18:29:50] WARNING: pid3138: Gumtree... OK 3356ms 
[04.05.2023 18:29:50] WARNING: pid3138: Mapping... OK 199ms 
[04.05.2023 18:29:50] WARNING: pid3138: Change graph building... OK 3783ms 
[04.05.2023 18:29:50] WARNING: pid3138: Change graph building... 
[04.05.2023 18:29:51] WARNING: pid3138: Flow graphs... OK 110ms 
[04.05.2023 18:29:54] WARNING: pid3138: Gumtree... OK 3313ms 
[04.05.2023 18:29:54] WARNING: pid3138: Mapping... OK 199ms 
[04.05.2023 18:29:54] WARNING: pid3138: Change graph building... OK 3728ms 
[04.05.2023 18:29:54] WARNING: Total pairs after the first step = 0 
[04.05.2023 18:29:54] WARNING: Done patterns' mining, total count = 0 
[04.05.2023 18:29:54] WARNING: Done filtering, total count = 0 
[04.05.2023 18:29:54] WARNING: No patterns were found 

The files differ in the following if-statement:

![Screenshot 2023-05-04 at 6 35 18 PM](https://user-images.githubusercontent.com/72650016/236180532-21ad11c8-b04b-4414-963f-a202ead24ec4.png)

Where am I going wrong? should I maybe use a later GumTree version?
I would very much appreciate any help!
Thank you!

**Comment by abiUni** [comment]
Hello,
I dug a bit deeper and it seems that Class nodes are not properly mapped from Gumtree and as a result the pfg cannot be built:

![Screenshot 2023-06-07 at 3 35 11 PM](https://github.com/JetBrains-Research/python-change-miner/assets/72650016/76e2bd30-d2c5-4a6c-8f4a-b10970eb987d)


Could you please provide any pointers why this could be happening and how it can be fixed??

Thank you!

**Comment by stspbu** [comment]
Hello,

If you try to run the tool on your examples in pfg mode (which just converts the AST of the given source file into a graph), you won't get any nodes associated with your class. And this is actually to be **expected**, because ClassDef nodes were never supported. At the top level, the tool operates with functions. Moreover, if you're mining not from repositories, but from your local files, only the first function will be processed for each of them (if any, otherwise the module itself is considered a function). Look [here](https://github.com/JetBrains-Research/python-change-miner/blob/master/pyflowgraph/build.py#L551) for more details.

However, if you run patterns mining from a git repository, your class methods will be processed, but again, separetely, without any class context. You can verify it [here](https://github.com/JetBrains-Research/python-change-miner/blob/1469425408f0372641473ca87b7ffcde0dffb71a/vcs/traverse.py#L290) (visiting ClassDef), and [here](https://github.com/JetBrains-Research/python-change-miner/blob/1469425408f0372641473ca87b7ffcde0dffb71a/vcs/traverse.py#L188) (iterating over functions). 

The reason for this behaviour is that the main goal of the project, as far as I remember, was to analyze code changes from commits. Patterns mining from local files has been added for manual testing, and was not intended to be used as an independent process.

I don't know exactly your use case, but:
- If you just want to test how it works, you should write one function in your test files / write code directly at the module level (examples can be found in [tests](https://github.com/JetBrains-Research/python-change-miner/blob/master/tests/test_pyflowgraph.py#L87))
- If you really need to mine patterns from local files, you can reuse [this approach](https://github.com/JetBrains-Research/python-change-miner/blob/1469425408f0372641473ca87b7ffcde0dffb71a/vcs/traverse.py#L183)
- If you need to extend the context to the class / module level or even further, you must improve the current implementation. A good one should maintain dependencies between classes and instances, and can therefore be quite tricky and time consuming. 

---

Please note that the tool also doesn't support some of the "basic" parts of the AST, such as SetComp, Yield, Match (which were added in 3.10, while the project was targetting mainly 3.8), etc. More details can be found [here](https://github.com/JetBrains-Research/python-change-miner/blob/0bb6f7b6663daf0987882fa36af15a8cf90cc4df/pyflowgraph/build.py) comparing the implementation with the latest [AST docs](https://docs.python.org/3/library/ast.html).

P.S. I haven't worked on the project for over 3 years and it looks like the company eventually stopped developing it. Unfortunately I can't tell you if this will ever change, but I can still give you some advice and maybe review your code if needed.

**Comment by abiUni** [comment]
Thank you so much for your response! 
I have tried to use the tool on a git repository, however the errors still persist regarding ClassDef.

> Please note that the tool also doesn't support some of the "basic" parts of the AST, such as SetComp, Yield, Match (which were added in 3.10, while the project was targetting mainly 3.8), etc. More details can be found [here](https://github.com/JetBrains-Research/python-change-miner/blob/0bb6f7b6663daf0987882fa36af15a8cf90cc4df/pyflowgraph/build.py) comparing the implementation with the latest [AST docs](https://docs.python.org/3/library/ast.html).

I am also getting errors with Match and Yield and I  will try to detect the python version in advance.
I will continue investigating the full set of problems taking into account the tool limitations that you mentioned and get back to you.

Thanks again for your time and support 🙏 !!

**Comment by stspbu** [comment]
> Thank you so much for your response! I have tried to use the tool on a git repository, however the errors still persist regarding ClassDef.
> 
> > Please note that the tool also doesn't support some of the "basic" parts of the AST, such as SetComp, Yield, Match (which were added in 3.10, while the project was targetting mainly 3.8), etc. More details can be found [here](https://github.com/JetBrains-Research/python-change-miner/blob/0bb6f7b6663daf0987882fa36af15a8cf90cc4df/pyflowgraph/build.py) comparing the implementation with the latest [AST docs](https://docs.python.org/3/library/ast.html).
> 
> I am also getting errors with Match and Yield and I will try to detect the python version in advance. I will continue investigating the full set of problems taking into account the tool limitations that you mentioned and get back to you.
> 
> Thanks again for your time and support 🙏 !!

As I mentioned above, the tool works at the function level, so 'ClassDef' won't be taken into account in any mode, but class functions will be processed (separately, w/o the class context) if you run the commit history analysis from git-repositories.

You usually don't need to worry about unsupported nodes, unless you really want to research the patterns that include them. As far as I remember, the presence of such nodes will be ignored, change graphs will be built by the remaining context, and some patterns (if any) will eventually be found. Also, note that Python's AST doesn't change much from version to version (and the old functionality is still compatible), so there should be no difference for most of the code even if you're analysing the latest stable release (3.11 as of today).
